#! /bin/sh

sxhkd &
#polybar &
feh --bg-fill ~/.config/wallpaper.jpg &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
